apiVersion: apps/v1
kind: Deployment
metadata:
  name: whydah
spec:
  replicas: 1
  selector:
    matchLabels:
      app: whydah
  template:
    metadata:
      labels:
        app: whydah
    spec:
      containers:
      - name: whydah
        image: ghcr.io/ccollicutt/whydah:latest