apiVersion: v1
kind: Service
metadata:
  name: whydah
  labels:
    app: whydah
spec:
  selector:
    app: whydah
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer

